image: node:8
pipelines:
 branches:
   master:
     - step:
         deployment: production
         caches:
           - node
         script: # Modify the commands below to build your repository.
           - npm install
           - npm install -g @angular/cli
           - ng build 
           - yarn deploy
